
javascripts:
  - 'lib/jquery.js'
  - 'lib/underscore.js'
  - 'lib/backbone.js'
  - 'app/controllers/*.coffee'
  - 'app/views/**/*.coffee'
  - 'app/models/*.coffee'

stylesheets:
  - 'public/stylesheets/*.less'

specs:
  - 'spec/*/*.coffee'
  - 'spec/views/*/*.coffee'
  
templates:
  - 'app/templates/*/*.eco'